/* 2020-2026 Quantum Resistant Cryptographic Solutions Corporation
 * All Rights Reserved.
 *
 * NOTICE:
 * This software and all accompanying materials are the exclusive property of
 * Quantum Resistant Cryptographic Solutions Corporation (QRCS). The intellectual
 * and technical concepts contained herein are proprietary to QRCS and are
 * protected under applicable Canadian, U.S., and international copyright,
 * patent, and trade secret laws.
 *
 * CRYPTOGRAPHIC ALGORITHMS AND IMPLEMENTATIONS:
 * - This software includes implementations of cryptographic primitives and
 *   algorithms that are standardized or in the public domain, such as AES
 *   and SHA-3, which are not proprietary to QRCS.
 * - This software also includes cryptographic primitives, constructions, and
 *   algorithms designed by QRCS, including but not limited to RCS, SCB, CSX, QMAC, and
 *   related components, which are proprietary to QRCS.
 * - All source code, implementations, protocol compositions, optimizations,
 *   parameter selections, and engineering work contained in this software are
 *   original works of QRCS and are protected under this license.
 *
 * LICENSE AND USE RESTRICTIONS:
 * - This software is licensed under the Quantum Resistant Cryptographic Solutions
 *   Public Research and Evaluation License (QRCS-PREL), 2025-2026.
 * - Permission is granted solely for non-commercial evaluation, academic research,
 *   cryptographic analysis, interoperability testing, and feasibility assessment.
 * - Commercial use, production deployment, commercial redistribution, or
 *   integration into products or services is strictly prohibited without a
 *   separate written license agreement executed with QRCS.
 * - Licensing and authorized distribution are solely at the discretion of QRCS.
 *
 * EXPERIMENTAL CRYPTOGRAPHY NOTICE:
 * Portions of this software may include experimental, novel, or evolving
 * cryptographic designs. Use of this software is entirely at the user's risk.
 *
 * DISCLAIMER:
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE, SECURITY, OR NON-INFRINGEMENT. QRCS DISCLAIMS ALL
 * LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING FROM THE USE OR MISUSE OF THIS SOFTWARE.
 *
 * FULL LICENSE:
 * This software is subject to the Quantum Resistant Cryptographic Solutions
 * Public Research and Evaluation License (QRCS-PREL), 2025-2026. The complete license terms
 * are provided in the accompanying LICENSE file or at https://www.qrcscorp.ca.
 *
 * Written by: John G. Underhill
 * Contact: contact@qrcscorp.ca
 */

#ifndef QSCTEST_X509_STAGE3_POSITIVE_INTEROP_TESTS_H
#define QSCTEST_X509_STAGE3_POSITIVE_INTEROP_TESTS_H

#include "qsccommon.h"

/**
 * \file x509_stage3_positive_interop_tests.h
 * \brief X.509 Stage 3 Positive Interoperability Test Interface.
 *
 * Declares the stage 3 X.509 positive interoperability test entry point. 
 * This stage is used to validate successful processing of correct certificates, 
 * chains, and related objects under expected interoperability scenarios. 
 * The function returns true only when all positive interoperability tests succeed.
 */

/**
 * \brief Tests verification of a server certificate chain generated by OpenSSL.
 *
 * \details
 * This test validates interoperability with externally generated certificates by
 * verifying a server chain produced using OpenSSL. It ensures that the X.509
 * implementation correctly parses, builds, and validates the chain according to
 * standard verification rules, including signature validation, trust anchoring,
 * and server authentication constraints.
 *
 * \return
 * true if the OpenSSL-generated server chain verifies successfully; false otherwise.
 */
bool x509_stage3_openssl_server_chain_ok(void);

/**
 * \brief Tests verification of a client certificate chain generated by OpenSSL.
 *
 * \details
 * This test ensures correct validation of a client authentication certificate
 * chain produced by OpenSSL. It verifies proper enforcement of client-specific
 * Extended Key Usage (EKU) constraints and confirms compatibility with external
 * certificate generation tools.
 *
 * \return
 * true if the OpenSSL-generated client chain verifies successfully; false otherwise.
 */
bool x509_stage3_openssl_client_chain_ok(void);

/**
 * \brief Tests decoding of UTCTime fields as defined in RFC 5280.
 *
 * \details
 * This test validates correct parsing of ASN.1 UTCTime values used in certificate
 * validity fields. It ensures compliance with RFC 5280 encoding rules, including
 * correct interpretation of year, timezone, and boundary conditions.
 *
 * \return
 * true if UTCTime values are decoded correctly; false otherwise.
 */
bool x509_stage3_rfc5280_utctime_decode(void);

/**
 * \brief Tests decoding of GeneralizedTime fields as defined in RFC 5280.
 *
 * \details
 * This test verifies correct handling of ASN.1 GeneralizedTime encoding used in
 * certificate validity fields. It ensures accurate parsing of extended year
 * formats, timezone normalization, and compliance with RFC 5280 requirements.
 *
 * \return
 * true if GeneralizedTime values are decoded correctly; false otherwise.
 */
bool x509_stage3_rfc5280_generalizedtime_decode(void);

/**
 * \brief Tests verification of a known-good Certificate Signing Request (CSR).
 *
 * \details
 * This test validates that a CSR with a known valid signature and structure
 * is correctly verified. It ensures proper parsing of the CSR, extraction of
 * subject and public key information, and successful signature verification.
 *
 * \return
 * true if the CSR verifies successfully; false otherwise.
 */
bool x509_stage3_csr_verify_known_good(void);

/**
 * \brief Tests verification of a known-good Certificate Revocation List (CRL).
 *
 * \details
 * This test verifies that a CRL with a valid signature and structure is correctly
 * parsed and authenticated. It ensures proper CRL signature verification using
 * the issuer certificate and correct interpretation of revocation entries.
 *
 * \return
 * true if the CRL verifies successfully; false otherwise.
 */
bool x509_stage3_crl_verify_known_good(void);

/**
 * \brief Tests decoding of a known-good DER-encoded certificate.
 *
 * \details
 * This test validates that a correctly encoded DER certificate can be parsed
 * without error. It ensures accurate decoding of the ASN.1 structure, including
 * subject, issuer, validity, public key, and extensions.
 *
 * \return
 * true if the DER certificate is decoded successfully; false otherwise.
 */
bool x509_stage3_der_certificate_decode_known_good(void);


/**
 * \brief Tests RFC 9879 PKCS #12 PBMAC1 interoperability vectors.
 *
 * \details
 * This test validates PBMAC1-based PKCS #12 MAC verification using the
 * official RFC 9879 Appendix A vectors. RFC 9879 obsoletes RFC 9579 and
 * specifies PBMAC1 use inside PKCS #12 syntax; passwords for PBMAC1 are
 * encoded as UTF-8 without a trailing NULL or BOM.
 *
 * Reference: https://www.rfc-editor.org/rfc/rfc9879.html#appendix-A
 *
 * \return
 * true if the valid RFC vectors verify and malformed negative vectors fail; otherwise false.
 */
bool x509_stage3_pkcs12_bundle_parse_profile(void);
bool x509_stage3_pkcs12_bundle_negative_cases(void);
bool x509_stage3_pkcs12_plain_and_nested_safe_contents(void);
bool x509_stage3_pkcs12_encrypted_private_key_cases(void);
bool x509_stage3_pkcs12_pbmac1_rfc9879_vectors(void);

/**
 * \brief Execute the x.509 stage 3 positive interoperability test.
 *
 * Runs the complete test set associated with this stage of the X.509 test
 * framework.
 *
 * \return Returns true if the full stage passes; otherwise returns false.
 */
bool qsctest_x509_stage3_positive_interop_tests(void);

#endif
