/**
* \file aes_test.h
* \brief AES Known Answer Tests \n
* Rijndael known answer comparison (KAT) tests. \n
* The AES test vectors are from the NIST standard tests contained in AES specification document, Appendix C. \n
* FIPS 197: <a href="http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf">The Advanced Encryption Standard</a>. \n
* \author John Underhill
* \date October 12, 2020
* \updated December 05, 2020
*/

#ifndef QSCTEST_RHX_TEST_H
#define QSCTEST_RHX_TEST_H

#include "common.h"
#include "../QSC/aes.h"

#if defined(QSC_SYSTEM_AESNI_ENABLED) 
#	if defined(QSC_SYSTEM_HAS_AVX512)
#		define RHX_WIDE_BLOCK_TESTS
#	endif
#endif

/**
* \brief Tests the qsc_aes_mode_cbc 128bit key KAT vectors from NIST SP800-85a.
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* SP800-38a: <a href="http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf">Block Cipher Modes of Operations</a>
*/
bool qsctest_fips_aes128_cbc(void);

/**
* \brief Tests the qsc_aes_mode_cbc 256-bit key KAT vectors from NIST SP800-85a.
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* SP800-38a: <a href="http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf">Block Cipher Modes of Operations</a>
*/
bool qsctest_fips_aes256_cbc(void);

/**
* \brief Tests the qsc_aes_mode_ctr 128bit key KAT vectors from NIST SP800-85a.
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* SP800-38a: <a href="http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf">Block Cipher Modes of Operations</a>
*/
bool qsctest_fips_aes128_ctr(void);

/**
* \brief Tests the qsc_aes_mode_ctr 128bit key KAT vectors from NIST SP800-85a.
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* SP800-38a: <a href="http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf">Block Cipher Modes of Operations</a>
*/
bool qsctest_fips_aes256_ctr(void);

/**
* \brief Tests the qsc_aes_mode_ecb mode 128bit key KAT vectors from NIST FIPS197 and SP800-85a
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* Fips197: <a href="http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf">The Advanced Encryption Standard, Appendix C.1</a>
* SP800-38a: <a href="http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf">Block Cipher Modes of Operations</a>
*/
bool qsctest_fips_aes128_ecb(void);

/**
* \brief Tests the qsc_aes_mode_ecb 256-bit key KAT vectors from NIST FIPS197 and SP800-85a.
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* Fips197: <a href="http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf">The Advanced Encryption Standard, Appendix C.3</a>
* SP800-38a: <a href="http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf">Block Cipher Modes of Operations</a>
*/
bool qsctest_fips_aes256_ecb(void);

/**
* \brief Tests the Hash Based Authentication (HBA-RSX/RHX) AEAD mode using 256-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptographic library</a>
* If QSC_RHX_SHAKE_EXTENSION is defined in rhx.h (default) the cSHAKE extension is tested, if it is not defined, reverts to the HKDF(SHA2) extension.
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
*/
bool qsctest_aes256_hba_kat(void);

/**
* \brief Tests the HBA-RHX256 AEAD mode for correct operation.
*
* \return Returns true for success
*/
bool qsctest_aes256_hba_stress(void);

/**
* \brief Tests the padding functions for correct operation.
*
* \return Returns true for success
*/
bool qsctest_aes256_padding_test(void);

/**
* \brief Run the set of FIPS 197 AES tests
*/
void qsctest_aes_run(void);

#endif
