/* 2020-2026 Quantum Resistant Cryptographic Solutions Corporation
 * All Rights Reserved.
 *
 * NOTICE:
 * This software and all accompanying materials are the exclusive property of
 * Quantum Resistant Cryptographic Solutions Corporation (QRCS). The intellectual
 * and technical concepts contained herein are proprietary to QRCS and are
 * protected under applicable Canadian, U.S., and international copyright,
 * patent, and trade secret laws.
 *
 * CRYPTOGRAPHIC ALGORITHMS AND IMPLEMENTATIONS:
 * - This software includes implementations of cryptographic primitives and
 *   algorithms that are standardized or in the public domain, such as AES
 *   and SHA-3, which are not proprietary to QRCS.
 * - This software also includes cryptographic primitives, constructions, and
 *   algorithms designed by QRCS, including but not limited to RCS, SCB, CSX, QMAC, and
 *   related components, which are proprietary to QRCS.
 * - All source code, implementations, protocol compositions, optimizations,
 *   parameter selections, and engineering work contained in this software are
 *   original works of QRCS and are protected under this license.
 *
 * LICENSE AND USE RESTRICTIONS:
 * - This software is licensed under the Quantum Resistant Cryptographic Solutions
 *   Public Research and Evaluation License (QRCS-PREL), 2025-2026.
 * - Permission is granted solely for non-commercial evaluation, academic research,
 *   cryptographic analysis, interoperability testing, and feasibility assessment.
 * - Commercial use, production deployment, commercial redistribution, or
 *   integration into products or services is strictly prohibited without a
 *   separate written license agreement executed with QRCS.
 * - Licensing and authorized distribution are solely at the discretion of QRCS.
 *
 * EXPERIMENTAL CRYPTOGRAPHY NOTICE:
 * Portions of this software may include experimental, novel, or evolving
 * cryptographic designs. Use of this software is entirely at the user's risk.
 *
 * DISCLAIMER:
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE, SECURITY, OR NON-INFRINGEMENT. QRCS DISCLAIMS ALL
 * LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING FROM THE USE OR MISUSE OF THIS SOFTWARE.
 *
 * FULL LICENSE:
 * This software is subject to the Quantum Resistant Cryptographic Solutions
 * Public Research and Evaluation License (QRCS-PREL), 2025-2026. The complete license terms
 * are provided in the accompanying LICENSE file or at https://www.qrcscorp.ca.
 *
 * Written by: John G. Underhill
 * Contact: contact@qrcscorp.ca
 */

#ifndef QSC_CSP_H
#define QSC_CSP_H

#include "qsccommon.h"

QSC_CPLUSPLUS_ENABLED_START

/* bogus winbase.h error */
QSC_SYSTEM_CONDITION_IGNORE(5105)

/**
 * \file csp.h
 * \brief Cryptographic System Entropy Provider Header
 *
 * \details
 * This header provides the interface for the Cryptographic System Entropy Provider.
 * It offers access to pseudo-random data generated by the system's entropy source.
 * On Windows systems, the provider uses the CryptGenRandom API; on POSIX systems,
 * it reads from the /dev/urandom device. In environments where arc4random_buf is available,
 * that function is used directly.
 *
 * Example Usage:
 * \code
 *  #include "csp.h"
 *
 *  uint8_t buffer[64];
 *  if (qsc_csp_generate(buffer, sizeof(buffer)))
 *  {
 *      // buffer now contains 64 bytes of pseudo-random data.
 *  }
 *
 *  uint32_t randomValue = qsc_csp_uint32();
 * \endcode
 *
 * This provider is recommended to be combined with additional entropy sources
 * to ensure robust randomness.
 *
 * \section csp_links Reference Links
 * - <a href="https://docs.microsoft.com/en-us/windows/win32/seccrypto/cryptgenrandom">Microsoft CryptGenRandom Documentation</a>
 * - <a href="https://pubs.opengroup.org/onlinepubs/9699919799/functions/devurandom.html">POSIX /dev/urandom Documentation</a>
 */

/*!
 * \def QSC_CSP_SEED_MAX
 * \brief The maximum number of seed bytes that can be extracted from a single generate call.
 */
#define QSC_CSP_SEED_MAX 1024000U

/**
 * \brief Retrieve pseudo-random bytes from the system entropy provider.
 *
 * This function fills the provided output array with pseudo-random bytes sourced from
 * the operating system's entropy mechanism. On Windows systems, it utilizes the CryptGenRandom
 * function from the Windows API, whereas on Posix systems it reads from the /dev/urandom device.
 * In environments supporting arc4random_buf, that function is used directly.
 *
 * \param output:	[uint8_t*] Pointer to the byte array where the random data will be stored.
 * \param length:	[size_t] The number of random bytes to generate. Must not exceed QSC_CSP_SEED_MAX.
 *
 * \return			[bool] Returns true if the random data was successfully generated; otherwise, false.
 *
 * \see qsc_csp_uint16(), qsc_csp_uint32(), qsc_csp_uint64()
 */
QSC_EXPORT_API bool qsc_csp_generate(uint8_t* output, size_t length);

/**
 * \brief Generate a random 16-bit unsigned integer.
 *
 * This function generates a pseudo-random 16-bit unsigned integer by retrieving the appropriate
 * number of bytes from the system entropy provider.
 *
 * \return			[uint16_t] Returns the pseudo-random 16-bit unsigned integer.
 *
 * \see qsc_csp_generate()
 */
QSC_EXPORT_API uint16_t qsc_csp_uint16(void);

/**
 * \brief Generate a random 32-bit unsigned integer.
 *
 * This function generates a pseudo-random 32-bit unsigned integer by retrieving the appropriate
 * number of bytes from the system entropy provider.
 *
 * \return			[uint32_t] Returns the pseudo-random 32-bit unsigned integer.
 *
 * \see qsc_csp_generate()
 */
QSC_EXPORT_API uint32_t qsc_csp_uint32(void);

/**
 * \brief Generate a random 64-bit unsigned integer.
 *
 * This function generates a pseudo-random 64-bit unsigned integer by retrieving the appropriate
 * number of bytes from the system entropy provider.
 *
 * \return			[uint64_t] Returns the pseudo-random 64-bit unsigned integer.
 *
 * \see qsc_csp_generate()
 */
QSC_EXPORT_API uint64_t qsc_csp_uint64(void);

QSC_CPLUSPLUS_ENABLED_END

#endif
