#ifndef NEWHOPE_PARAMS_H
#define NEWHOPE_PARAMS_H

#define NEWHOPE_Q 12289 
/* used in noise sampling */
#define NEWHOPE_K 8
#define NEWHOPE_N 1024
/* size of shared key, seeds/coins, and hashes */
#define NEWHOPE_SYMBYTES 32
#define NEWHOPE_POLYBYTES ((14 * NEWHOPE_N) / 8)
#define NEWHOPE_POLYCOMPRESSEDBYTES ((3 * NEWHOPE_N) / 8)
#define NEWHOPE_CPAPKE_PUBLICKEYBYTES (NEWHOPE_POLYBYTES + NEWHOPE_SYMBYTES)
#define NEWHOPE_CPAPKE_SECRETKEYBYTES (NEWHOPE_POLYBYTES)
#define NEWHOPE_CPAPKE_CIPHERTEXTBYTES (NEWHOPE_POLYBYTES + NEWHOPE_POLYCOMPRESSEDBYTES)
#define NEWHOPE_CPAKEM_PUBLICKEYBYTES NEWHOPE_CPAPKE_PUBLICKEYBYTES
#define NEWHOPE_CPAKEM_SECRETKEYBYTES NEWHOPE_CPAPKE_SECRETKEYBYTES
#define NEWHOPE_CPAKEM_CIPHERTEXTBYTES NEWHOPE_CPAPKE_CIPHERTEXTBYTES

/*!
\def NEWHOPE_SHAREDSECRET_SIZE
* The byte size of the shared secret key
*/
#define NEWHOPE_SHAREDSECRET_SIZE NEWHOPE_SYMBYTES

/*!
\def NEWHOPE_PUBLICKEY_SIZE
* The byte size of the public key array
*/
#define NEWHOPE_PUBLICKEY_SIZE NEWHOPE_CPAPKE_PUBLICKEYBYTES

/*!
\def NEWHOPE_SECRETKEY_SIZE
* The byte size of the secret key array
*/
#define NEWHOPE_SECRETKEY_SIZE (NEWHOPE_CPAPKE_SECRETKEYBYTES + NEWHOPE_CPAPKE_PUBLICKEYBYTES + 2 * NEWHOPE_SYMBYTES)

/*!
\def NEWHOPE_CIPHERTEXT_SIZE
* The byte size of the cipher-text array
*/
#define NEWHOPE_CIPHERTEXT_SIZE (NEWHOPE_CPAPKE_CIPHERTEXTBYTES + NEWHOPE_SYMBYTES)

/*!
\def NEWHOPE_ALGNAME
* The NewHope implementation name
*/
#define NEWHOPE_ALGNAME "NewHope1024-CCAKEM"

#endif
